---
name: Main

permissions:
  contents: read

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: latest
          args: --timeout 5000s --verbose
          skip-cache: true
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
      - run: make build-all
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
      - run: make test
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod
      - run: sudo apt install -y whois
      - run: make build
      - run: |
          WHOISD_LISTEN=:10043 WHOISD_LOG_LEVEL=debug ./whoisd &
          sleep 1
          whois -h localhost -p 10043 example.com
  build-container:
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload container images to ghcr.io
      packages: write
      # Needed for attestation
      id-token: write
      attestations: write
      artifact-metadata: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        if: |
          github.repository == 'LamaCorp/whoisd' &&
            (github.event_name != 'pull_request' ||
             github.event.pull_request.head.repo.full_name == github.repository)
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        id: push
        with:
          file: Dockerfile
          context: .
          build-args: |
            VERSION=${{ github.event.pull_request.head.sha }}
            COMMIT=${{ github.event.pull_request.head.sha }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/lamacorp/whoisd-dev:${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          push: |
            ${{ github.repository == 'LamaCorp/whoisd' &&
              (github.event_name != 'pull_request' ||
              github.event.pull_request.head.repo.full_name == github.repository) }}
          cache-from: type=registry,ref=ghcr.io/lamacorp/whoisd-dev:buildcache
          cache-to: |
            ${{ (github.repository == 'LamaCorp/whoisd' &&
                (github.event_name != 'pull_request' ||
                  github.event.pull_request.head.repo.full_name == github.repository))
                && 'type=registry,ref=ghcr.io/lamacorp/whoisd-dev:buildcache,mode=max'
                || ''
            }}
      - uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
        id: attest
        if: |
          github.repository == 'LamaCorp/whoisd' &&
            (github.event_name != 'pull_request' ||
             github.event.pull_request.head.repo.full_name == github.repository)
        with:
          subject-name: ghcr.io/lamacorp/whoisd-dev
          subject-digest: "${{ steps.push.outputs.digest }}"
          push-to-registry: true
  ci-main-mark:
    if: always()
    needs:
      - lint
      - build
      - test-unit
      - test-integration
      - build-container
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
