---
name: Release

"on":
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 1.2.3). Do not prefix with a `v`"
        required: true
        type: string

jobs:
  binaries:
    permissions:
      # Needed for attestation
      id-token: write
      attestations: write
      artifact-metadata: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { goos: linux, goarch: amd64 }
          - { goos: linux, goarch: 386 }
          - { goos: linux, goarch: arm, goarm: "6" }
          - { goos: linux, goarch: arm64 }
          - { goos: windows, goarch: amd64 }
          - { goos: windows, goarch: 386 }
          - { goos: windows, goarch: arm, goarm: "6" }
          - { goos: windows, goarch: arm64 }
          - { goos: darwin, goarch: amd64 }
          - { goos: darwin, goarch: arm64 }
          - { goos: freebsd, goarch: amd64 }
          - { goos: freebsd, goarch: 386 }
          - { goos: freebsd, goarch: arm, goarm: "6" }
          - { goos: freebsd, goarch: arm64 }
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: ${{ github.sha }}
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
      - id: names
        shell: bash
        run: |
          BINARY_NAME=whoisd
          ARCHIVE_NAME="${BINARY_NAME}-v${{ inputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            echo "binary=${BINARY_NAME}.exe" >> "$GITHUB_OUTPUT"
            echo "archive=${ARCHIVE_NAME}.zip" >> "$GITHUB_OUTPUT"
          else
            echo "binary=${BINARY_NAME}" >> "$GITHUB_OUTPUT"
            echo "archive=${ARCHIVE_NAME}.tar.gz" >> "$GITHUB_OUTPUT"
          fi
      - name: build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
          CGO_ENABLED: "0"
        run: |
          go build \
            -trimpath \
            -ldflags="-s -w -X main.version=v${{ inputs.version }} -X main.commit=${{ github.sha }}" \
            -o dist/${{ steps.names.outputs.binary }} \
            ./...
      - name: archive
        if: "matrix.goos != 'windows'"
        run: tar -czf dist/${{ steps.names.outputs.archive }} -C dist ${{ steps.names.outputs.binary }}
      - name: archive
        if: "matrix.goos == 'windows'"
        run: cd dist && zip ${{ steps.names.outputs.archive }} ${{ steps.names.outputs.binary }}
      - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: dist/${{ steps.names.outputs.archive }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ steps.names.outputs.archive }}
          path: dist/${{ steps.names.outputs.archive }}
          if-no-files-found: error
          retention-days: 7
  container:
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload container images to ghcr.io
      packages: write
      # Needed for attestation
      id-token: write
      attestations: write
      artifact-metadata: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: ${{ github.sha }}
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        id: push
        with:
          file: Dockerfile
          context: .
          build-args: |
            VERSION=${{ inputs.version }}
            COMMIT=${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/lamacorp/whoisd:v${{ inputs.version }}
          push: true
      - uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        id: attest
        with:
          subject-name: ghcr.io/lamacorp/whoisd
          subject-digest: "${{ steps.push.outputs.digest }}"
          push-to-registry: true
  release:
    runs-on: ubuntu-latest
    permissions:
      # Needed to create the release
      contents: write
    needs:
      - binaries
      - container
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: ${{ github.sha }}
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist
          merge-multiple: true
      - working-directory: dist
        run: |
          rm *.dockerbuild
          sha256sum * > checksums.txt
      - uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3
        with:
          target_commitish: ${{ github.sha }}
          tag_name: v${{ inputs.version }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            dist/**
            LICENSE
